all:
	g++ src/spritepack.cpp -o bin/spritepack.e `gorgon-config --libs --addons`
	g++ src/animationpack_lua_to_gorgon.cpp -o bin/animationpack_lua_to_gorgon.e `gorgon-config --libs --addons`
#	g++ src/image.cpp -o bin/image.e `gorgon-config --libs --addons`
#	g++ src/sprite.cpp -o bin/sprite.e `gorgon-config --libs --addons`
